(define (problem p7) (:domain courses)
	(:objects
		adv-higher higher national-five national-four - nq
		year-one year-two year-three - bge
		english esol - english-literacy
		drama art-design music music-tech dance - expressive-arts
		phys-ed home-economics textiles - health-wellbeing
		maths numeracy lifeskills - maths-numeracy
		french german spanish italian latin mandarin cantonese gaelic urdu - languages
		biology chemistry physics landscape-gardening - sciences
		geography history modern-studies rmps philosophy politics - social-subjects
		admin-it business-management comp-sci design-manufacture graph-comm practical-woodwork pc-passport - technologies
		esme harper henry george erin zara ella caleb - student
	)

	(:init
		(= (cost) 0)
		(= (max-units) 4)
		(= (max-weeks) 8)
		
		(= (week esme music higher) 0)
		(= (unit esme music higher) 0)
		(= (extra-curricular esme music higher) 0)

		(= (week esme french national-four) 0)
		(= (unit esme french national-four) 0)
		(= (extra-curricular esme french national-four) 0)

		(= (week esme german national-four) 0)
		(= (unit esme german national-four) 0)
		(= (extra-curricular esme german national-four) 0)

		(= (week esme geography year-one) 0)
		(= (unit esme geography year-one) 0)
		(= (extra-curricular esme geography year-one) 0)

		(= (week esme music-tech national-four) 0)
		(= (unit esme music-tech national-four) 0)
		(= (extra-curricular esme music-tech national-four) 0)

		(= (week harper landscape-gardening national-five) 0)
		(= (unit harper landscape-gardening national-five) 0)
		(= (extra-curricular harper landscape-gardening national-five) 0)

		(= (week harper landscape-gardening adv-higher) 0)
		(= (unit harper landscape-gardening adv-higher) 0)
		(= (extra-curricular harper landscape-gardening adv-higher) 0)

		(= (week harper music year-two) 0)
		(= (unit harper music year-two) 0)
		(= (extra-curricular harper music year-two) 0)

		(= (week harper graph-comm higher) 0)
		(= (unit harper graph-comm higher) 0)
		(= (extra-curricular harper graph-comm higher) 0)

		(= (week harper gaelic year-one) 0)
		(= (unit harper gaelic year-one) 0)
		(= (extra-curricular harper gaelic year-one) 0)

		(= (week henry chemistry adv-higher) 0)
		(= (unit henry chemistry adv-higher) 0)
		(= (extra-curricular henry chemistry adv-higher) 0)

		(= (week henry comp-sci adv-higher) 0)
		(= (unit henry comp-sci adv-higher) 0)
		(= (extra-curricular henry comp-sci adv-higher) 0)

		(= (week henry modern-studies adv-higher) 0)
		(= (unit henry modern-studies adv-higher) 0)
		(= (extra-curricular henry modern-studies adv-higher) 0)

		(= (week henry gaelic year-two) 0)
		(= (unit henry gaelic year-two) 0)
		(= (extra-curricular henry gaelic year-two) 0)

		(= (week henry philosophy adv-higher) 0)
		(= (unit henry philosophy adv-higher) 0)
		(= (extra-curricular henry philosophy adv-higher) 0)

		(= (week george textiles year-two) 0)
		(= (unit george textiles year-two) 0)
		(= (extra-curricular george textiles year-two) 0)

		(= (week george dance year-two) 0)
		(= (unit george dance year-two) 0)
		(= (extra-curricular george dance year-two) 0)

		(= (week george philosophy adv-higher) 0)
		(= (unit george philosophy adv-higher) 0)
		(= (extra-curricular george philosophy adv-higher) 0)

		(= (week george phys-ed year-one) 0)
		(= (unit george phys-ed year-one) 0)
		(= (extra-curricular george phys-ed year-one) 0)

		(= (week george admin-it year-two) 0)
		(= (unit george admin-it year-two) 0)
		(= (extra-curricular george admin-it year-two) 0)

		(= (week erin chemistry year-two) 0)
		(= (unit erin chemistry year-two) 0)
		(= (extra-curricular erin chemistry year-two) 0)

		(= (week erin politics year-two) 0)
		(= (unit erin politics year-two) 0)
		(= (extra-curricular erin politics year-two) 0)

		(= (week erin comp-sci national-four) 0)
		(= (unit erin comp-sci national-four) 0)
		(= (extra-curricular erin comp-sci national-four) 0)

		(= (week erin graph-comm national-four) 0)
		(= (unit erin graph-comm national-four) 0)
		(= (extra-curricular erin graph-comm national-four) 0)

		(= (week erin design-manufacture adv-higher) 0)
		(= (unit erin design-manufacture adv-higher) 0)
		(= (extra-curricular erin design-manufacture adv-higher) 0)

		(= (week zara maths year-two) 0)
		(= (unit zara maths year-two) 0)
		(= (extra-curricular zara maths year-two) 0)

		(= (week zara landscape-gardening year-three) 0)
		(= (unit zara landscape-gardening year-three) 0)
		(= (extra-curricular zara landscape-gardening year-three) 0)

		(= (week zara mandarin national-four) 0)
		(= (unit zara mandarin national-four) 0)
		(= (extra-curricular zara mandarin national-four) 0)

		(= (week zara esol year-one) 0)
		(= (unit zara esol year-one) 0)
		(= (extra-curricular zara esol year-one) 0)

		(= (week zara graph-comm year-three) 0)
		(= (unit zara graph-comm year-three) 0)
		(= (extra-curricular zara graph-comm year-three) 0)

		(= (week ella textiles adv-higher) 0)
		(= (unit ella textiles adv-higher) 0)
		(= (extra-curricular ella textiles adv-higher) 0)

		(= (week ella music year-three) 0)
		(= (unit ella music year-three) 0)
		(= (extra-curricular ella music year-three) 0)

		(= (week ella french higher) 0)
		(= (unit ella french higher) 0)
		(= (extra-curricular ella french higher) 0)

		(= (week ella music-tech year-two) 0)
		(= (unit ella music-tech year-two) 0)
		(= (extra-curricular ella music-tech year-two) 0)

		(= (week ella italian national-five) 0)
		(= (unit ella italian national-five) 0)
		(= (extra-curricular ella italian national-five) 0)

		(= (week caleb home-economics year-one) 0)
		(= (unit caleb home-economics year-one) 0)
		(= (extra-curricular caleb home-economics year-one) 0)

		(= (week caleb business-management adv-higher) 0)
		(= (unit caleb business-management adv-higher) 0)
		(= (extra-curricular caleb business-management adv-higher) 0)

		(= (week caleb textiles national-five) 0)
		(= (unit caleb textiles national-five) 0)
		(= (extra-curricular caleb textiles national-five) 0)

		(= (week caleb gaelic national-five) 0)
		(= (unit caleb gaelic national-five) 0)
		(= (extra-curricular caleb gaelic national-five) 0)

		(= (week caleb chemistry national-five) 0)
		(= (unit caleb chemistry national-five) 0)
		(= (extra-curricular caleb chemistry national-five) 0)

		(takes-course esme music higher)
		(grade d esme music higher)
		(takes-course esme french national-four)
		(grade p esme french national-four)
		(takes-course esme german national-four)
		(grade p esme german national-four)
		(takes-course esme geography year-one)
		(grade p esme geography year-one)
		(takes-course esme music-tech national-four)
		(grade p esme music-tech national-four)
		(uses-strategy esme blended-learning)
		(takes-course harper landscape-gardening national-five)
		(grade c harper landscape-gardening national-five)
		(takes-course harper landscape-gardening adv-higher)
		(grade c harper landscape-gardening adv-higher)
		(takes-course harper music year-two)
		(grade p harper music year-two)
		(takes-course harper graph-comm higher)
		(grade b harper graph-comm higher)
		(takes-course harper gaelic year-one)
		(grade p harper gaelic year-one)
		(uses-strategy harper project-based)
		(takes-course henry chemistry adv-higher)
		(grade b henry chemistry adv-higher)
		(takes-course henry comp-sci adv-higher)
		(grade b henry comp-sci adv-higher)
		(takes-course henry modern-studies adv-higher)
		(grade b henry modern-studies adv-higher)
		(takes-course henry gaelic year-two)
		(grade p henry gaelic year-two)
		(takes-course henry philosophy adv-higher)
		(grade b henry philosophy adv-higher)
		(uses-strategy henry blended-learning)
		(takes-course george textiles year-two)
		(grade p george textiles year-two)
		(takes-course george dance year-two)
		(grade p george dance year-two)
		(takes-course george philosophy adv-higher)
		(grade d george philosophy adv-higher)
		(takes-course george phys-ed year-one)
		(grade p george phys-ed year-one)
		(takes-course george admin-it year-two)
		(grade p george admin-it year-two)
		(uses-strategy george gamification)
		(takes-course erin chemistry year-two)
		(grade p erin chemistry year-two)
		(takes-course erin politics year-two)
		(grade p erin politics year-two)
		(takes-course erin comp-sci national-four)
		(grade p erin comp-sci national-four)
		(takes-course erin graph-comm national-four)
		(grade p erin graph-comm national-four)
		(takes-course erin design-manufacture adv-higher)
		(grade c erin design-manufacture adv-higher)
		(uses-strategy erin flex-seating)
		(takes-course zara maths year-two)
		(grade p zara maths year-two)
		(takes-course zara landscape-gardening year-three)
		(grade p zara landscape-gardening year-three)
		(takes-course zara mandarin national-four)
		(grade p zara mandarin national-four)
		(takes-course zara esol year-one)
		(grade p zara esol year-one)
		(takes-course zara graph-comm year-three)
		(grade p zara graph-comm year-three)
		(uses-strategy zara gamification)
		(takes-course ella textiles adv-higher)
		(grade a ella textiles adv-higher)
		(takes-course ella music year-three)
		(grade p ella music year-three)
		(takes-course ella french higher)
		(grade c ella french higher)
		(takes-course ella music-tech year-two)
		(grade p ella music-tech year-two)
		(takes-course ella italian national-five)
		(grade a ella italian national-five)
		(uses-strategy ella project-based)
		(takes-course caleb home-economics year-one)
		(grade p caleb home-economics year-one)
		(takes-course caleb business-management adv-higher)
		(grade d caleb business-management adv-higher)
		(takes-course caleb textiles national-five)
		(grade b caleb textiles national-five)
		(takes-course caleb gaelic national-five)
		(grade b caleb gaelic national-five)
		(takes-course caleb chemistry national-five)
		(grade c caleb chemistry national-five)
		(uses-strategy caleb blended-learning)
	)

	(:goal
		(and
			(finished-course esme music higher)
			(finished-course esme french national-four)
			(finished-course esme german national-four)
			(finished-course esme geography year-one)
			(finished-course esme music-tech national-four)
			(given-support esme improving-comms-workshop)
			(given-support esme tech-assist)
			(given-support esme gamify-learning)
			(finished-course harper landscape-gardening national-five)
			(finished-course harper landscape-gardening adv-higher)
			(finished-course harper music year-two)
			(finished-course harper graph-comm higher)
			(finished-course harper gaelic year-one)
			(given-support harper improving-comms-workshop)
			(finished-course henry chemistry adv-higher)
			(finished-course henry comp-sci adv-higher)
			(finished-course henry modern-studies adv-higher)
			(finished-course henry gaelic year-two)
			(finished-course henry philosophy adv-higher)
			(given-support henry improving-comms-workshop)
			(given-support henry tech-assist)
			(given-support henry gamify-learning)
			(finished-course george textiles year-two)
			(finished-course george dance year-two)
			(finished-course george philosophy adv-higher)
			(finished-course george phys-ed year-one)
			(finished-course george admin-it year-two)
			(given-support george gamify-learning)
			(finished-course erin chemistry year-two)
			(finished-course erin politics year-two)
			(finished-course erin comp-sci national-four)
			(finished-course erin graph-comm national-four)
			(finished-course erin design-manufacture adv-higher)
			(given-support erin improving-comms-workshop)
			(finished-course zara maths year-two)
			(finished-course zara landscape-gardening year-three)
			(finished-course zara mandarin national-four)
			(finished-course zara esol year-one)
			(finished-course zara graph-comm year-three)
			(given-support zara gamify-learning)
			(finished-course ella textiles adv-higher)
			(finished-course ella music year-three)
			(finished-course ella french higher)
			(finished-course ella music-tech year-two)
			(finished-course ella italian national-five)
			(given-support ella improving-comms-workshop)
			(finished-course caleb home-economics year-one)
			(finished-course caleb business-management adv-higher)
			(finished-course caleb textiles national-five)
			(finished-course caleb gaelic national-five)
			(finished-course caleb chemistry national-five)
			(given-support caleb improving-comms-workshop)
			(given-support caleb tech-assist)
			(given-support caleb gamify-learning)
		)
	)

	(:metric minimize (cost))
)
