(define (problem p7) (:domain courses)
	(:objects
		adv-higher higher national-five national-four - nq
		year-one year-two year-three - bge
		english esol - english-literacy
		drama art-design music music-tech dance - expressive-arts
		phys-ed home-economics textiles - health-wellbeing
		maths numeracy lifeskills - maths-numeracy
		french german spanish italian latin mandarin cantonese gaelic urdu - languages
		biology chemistry physics landscape-gardening - sciences
		geography history modern-studies rmps philosophy politics - social-subjects
		admin-it business-management comp-sci design-manufacture graph-comm practical-woodwork pc-passport - technologies
		esme harper henry george erin zara ella caleb beatrice louis evan matilda sebastian finn florence iris reuben eliza cody toby hannah scarlett oscar thea jacob elara layla jesse james ivy - student
	)

	(:init
		(= (cost) 0)
		(= (max-units) 4)
		(= (max-weeks) 8)
		(takes-course esme music higher)
		(grade d esme music higher)
		(takes-course esme french national-four)
		(grade p esme french national-four)
		(takes-course esme german national-four)
		(grade p esme german national-four)
		(takes-course esme geography year-one)
		(grade p esme geography year-one)
		(takes-course esme music-tech national-four)
		(grade p esme music-tech national-four)
		(uses-strategy esme blended-learning)
		(takes-course harper landscape-gardening national-five)
		(grade c harper landscape-gardening national-five)
		(takes-course harper landscape-gardening adv-higher)
		(grade c harper landscape-gardening adv-higher)
		(takes-course harper music year-two)
		(grade p harper music year-two)
		(takes-course harper graph-comm higher)
		(grade b harper graph-comm higher)
		(takes-course harper gaelic year-one)
		(grade p harper gaelic year-one)
		(uses-strategy harper project-based)
		(takes-course henry chemistry adv-higher)
		(grade b henry chemistry adv-higher)
		(takes-course henry comp-sci adv-higher)
		(grade b henry comp-sci adv-higher)
		(takes-course henry modern-studies adv-higher)
		(grade b henry modern-studies adv-higher)
		(takes-course henry gaelic year-two)
		(grade p henry gaelic year-two)
		(takes-course henry philosophy adv-higher)
		(grade b henry philosophy adv-higher)
		(uses-strategy henry blended-learning)
		(takes-course george textiles year-two)
		(grade p george textiles year-two)
		(takes-course george dance year-two)
		(grade p george dance year-two)
		(takes-course george philosophy adv-higher)
		(grade d george philosophy adv-higher)
		(takes-course george phys-ed year-one)
		(grade p george phys-ed year-one)
		(takes-course george admin-it year-two)
		(grade p george admin-it year-two)
		(uses-strategy george gamification)
		(takes-course erin chemistry year-two)
		(grade p erin chemistry year-two)
		(takes-course erin politics year-two)
		(grade p erin politics year-two)
		(takes-course erin comp-sci national-four)
		(grade p erin comp-sci national-four)
		(takes-course erin graph-comm national-four)
		(grade p erin graph-comm national-four)
		(takes-course erin design-manufacture adv-higher)
		(grade c erin design-manufacture adv-higher)
		(uses-strategy erin flex-seating)
		(takes-course zara maths year-two)
		(grade p zara maths year-two)
		(takes-course zara landscape-gardening year-three)
		(grade p zara landscape-gardening year-three)
		(takes-course zara mandarin national-four)
		(grade p zara mandarin national-four)
		(takes-course zara esol year-one)
		(grade p zara esol year-one)
		(takes-course zara graph-comm year-three)
		(grade p zara graph-comm year-three)
		(uses-strategy zara gamification)
		(takes-course ella textiles adv-higher)
		(grade a ella textiles adv-higher)
		(takes-course ella music year-three)
		(grade p ella music year-three)
		(takes-course ella french higher)
		(grade c ella french higher)
		(takes-course ella music-tech year-two)
		(grade p ella music-tech year-two)
		(takes-course ella italian national-five)
		(grade a ella italian national-five)
		(uses-strategy ella project-based)
		(takes-course caleb home-economics year-one)
		(grade p caleb home-economics year-one)
		(takes-course caleb business-management adv-higher)
		(grade d caleb business-management adv-higher)
		(takes-course caleb textiles national-five)
		(grade b caleb textiles national-five)
		(takes-course caleb gaelic national-five)
		(grade b caleb gaelic national-five)
		(takes-course caleb chemistry national-five)
		(grade c caleb chemistry national-five)
		(uses-strategy caleb blended-learning)
		(takes-course beatrice mandarin year-one)
		(grade p beatrice mandarin year-one)
		(takes-course beatrice urdu national-five)
		(grade d beatrice urdu national-five)
		(takes-course beatrice phys-ed year-three)
		(grade p beatrice phys-ed year-three)
		(takes-course beatrice pc-passport national-five)
		(grade a beatrice pc-passport national-five)
		(takes-course beatrice geography year-two)
		(grade p beatrice geography year-two)
		(uses-strategy beatrice teamwork)
		(takes-course louis spanish adv-higher)
		(grade c louis spanish adv-higher)
		(takes-course louis physics year-two)
		(grade p louis physics year-two)
		(takes-course louis landscape-gardening national-four)
		(grade p louis landscape-gardening national-four)
		(takes-course louis drama adv-higher)
		(grade c louis drama adv-higher)
		(takes-course louis rmps national-five)
		(grade d louis rmps national-five)
		(uses-strategy louis gamification)
		(takes-course evan german year-one)
		(grade p evan german year-one)
		(takes-course evan music year-one)
		(grade p evan music year-one)
		(takes-course evan maths year-one)
		(grade p evan maths year-one)
		(takes-course evan geography year-two)
		(grade p evan geography year-two)
		(takes-course evan politics national-four)
		(grade p evan politics national-four)
		(uses-strategy evan flex-seating)
		(takes-course matilda design-manufacture year-one)
		(grade p matilda design-manufacture year-one)
		(takes-course matilda biology year-three)
		(grade p matilda biology year-three)
		(takes-course matilda cantonese year-one)
		(grade p matilda cantonese year-one)
		(takes-course matilda biology national-four)
		(grade p matilda biology national-four)
		(takes-course matilda biology year-three)
		(grade p matilda biology year-three)
		(study-group biology year-three)
		(uses-strategy matilda teamwork)
		(takes-course sebastian geography national-five)
		(grade b sebastian geography national-five)
		(takes-course sebastian geography national-five)
		(grade d sebastian geography national-five)
		(takes-course sebastian philosophy national-four)
		(grade p sebastian philosophy national-four)
		(takes-course sebastian maths year-two)
		(grade p sebastian maths year-two)
		(takes-course sebastian admin-it national-five)
		(grade d sebastian admin-it national-five)
		(study-group geography national-five)
		(uses-strategy sebastian gamification)
		(takes-course finn biology higher)
		(grade c finn biology higher)
		(takes-course finn lifeskills national-four)
		(grade p finn lifeskills national-four)
		(takes-course finn biology national-four)
		(grade p finn biology national-four)
		(takes-course finn admin-it higher)
		(grade d finn admin-it higher)
		(takes-course finn physics year-two)
		(grade p finn physics year-two)
		(uses-strategy finn teamwork)
		(takes-course florence physics national-four)
		(grade p florence physics national-four)
		(takes-course florence design-manufacture national-four)
		(grade p florence design-manufacture national-four)
		(takes-course florence english national-five)
		(grade a florence english national-five)
		(takes-course florence rmps year-three)
		(grade p florence rmps year-three)
		(takes-course florence maths national-five)
		(grade b florence maths national-five)
		(uses-strategy florence project-based)
		(takes-course iris business-management adv-higher)
		(grade a iris business-management adv-higher)
		(takes-course iris practical-woodwork year-three)
		(grade p iris practical-woodwork year-three)
		(takes-course iris biology year-three)
		(grade p iris biology year-three)
		(takes-course iris rmps year-two)
		(grade p iris rmps year-two)
		(takes-course iris urdu higher)
		(grade d iris urdu higher)
		(uses-strategy iris flex-seating)
		(takes-course reuben esol year-one)
		(grade p reuben esol year-one)
		(takes-course reuben mandarin year-three)
		(grade p reuben mandarin year-three)
		(takes-course reuben esol national-four)
		(grade p reuben esol national-four)
		(takes-course reuben dance year-two)
		(grade p reuben dance year-two)
		(takes-course reuben italian adv-higher)
		(grade d reuben italian adv-higher)
		(uses-strategy reuben teamwork)
		(takes-course eliza italian year-one)
		(grade p eliza italian year-one)
		(takes-course eliza art-design national-five)
		(grade d eliza art-design national-five)
		(takes-course eliza phys-ed national-four)
		(grade p eliza phys-ed national-four)
		(takes-course eliza mandarin adv-higher)
		(grade a eliza mandarin adv-higher)
		(takes-course eliza italian year-one)
		(grade p eliza italian year-one)
		(study-group italian year-one)
		(uses-strategy eliza gamification)
		(takes-course cody english year-one)
		(grade p cody english year-one)
		(takes-course cody comp-sci national-four)
		(grade p cody comp-sci national-four)
		(takes-course cody home-economics year-three)
		(grade p cody home-economics year-three)
		(takes-course cody home-economics national-five)
		(grade d cody home-economics national-five)
		(takes-course cody drama national-four)
		(grade p cody drama national-four)
		(uses-strategy cody gamification)
		(takes-course toby numeracy higher)
		(grade c toby numeracy higher)
		(takes-course toby biology national-five)
		(grade c toby biology national-five)
		(takes-course toby italian adv-higher)
		(grade c toby italian adv-higher)
		(takes-course toby pc-passport higher)
		(grade c toby pc-passport higher)
		(takes-course toby admin-it adv-higher)
		(grade a toby admin-it adv-higher)
		(uses-strategy toby flex-seating)
		(takes-course hannah music national-four)
		(grade p hannah music national-four)
		(takes-course hannah phys-ed national-four)
		(grade p hannah phys-ed national-four)
		(takes-course hannah history year-three)
		(grade p hannah history year-three)
		(takes-course hannah italian national-four)
		(grade p hannah italian national-four)
		(takes-course hannah history year-one)
		(grade p hannah history year-one)
		(uses-strategy hannah project-based)
		(takes-course scarlett german year-two)
		(grade p scarlett german year-two)
		(takes-course scarlett urdu higher)
		(grade a scarlett urdu higher)
		(takes-course scarlett phys-ed higher)
		(grade c scarlett phys-ed higher)
		(takes-course scarlett politics year-one)
		(grade p scarlett politics year-one)
		(takes-course scarlett french year-two)
		(grade p scarlett french year-two)
		(uses-strategy scarlett gamification)
		(takes-course oscar french year-three)
		(grade p oscar french year-three)
		(takes-course oscar mandarin year-three)
		(grade p oscar mandarin year-three)
		(takes-course oscar history higher)
		(grade c oscar history higher)
		(takes-course oscar french year-three)
		(grade p oscar french year-three)
		(takes-course oscar french year-one)
		(grade p oscar french year-one)
		(study-group french year-three)
		(uses-strategy oscar project-based)
		(takes-course thea lifeskills year-two)
		(grade p thea lifeskills year-two)
		(takes-course thea practical-woodwork national-five)
		(grade a thea practical-woodwork national-five)
		(takes-course thea politics year-two)
		(grade p thea politics year-two)
		(takes-course thea design-manufacture year-one)
		(grade p thea design-manufacture year-one)
		(takes-course thea spanish year-three)
		(grade p thea spanish year-three)
		(uses-strategy thea teamwork)
		(takes-course jacob chemistry national-five)
		(grade b jacob chemistry national-five)
		(takes-course jacob rmps year-two)
		(grade p jacob rmps year-two)
		(takes-course jacob philosophy higher)
		(grade d jacob philosophy higher)
		(takes-course jacob music-tech year-one)
		(grade p jacob music-tech year-one)
		(takes-course jacob history adv-higher)
		(grade a jacob history adv-higher)
		(uses-strategy jacob technological-tools)
		(takes-course elara esol adv-higher)
		(grade a elara esol adv-higher)
		(takes-course elara numeracy year-three)
		(grade p elara numeracy year-three)
		(takes-course elara spanish higher)
		(grade d elara spanish higher)
		(takes-course elara graph-comm higher)
		(grade b elara graph-comm higher)
		(takes-course elara pc-passport national-five)
		(grade b elara pc-passport national-five)
		(uses-strategy elara teamwork)
		(takes-course layla practical-woodwork year-one)
		(grade p layla practical-woodwork year-one)
		(takes-course layla design-manufacture year-two)
		(grade p layla design-manufacture year-two)
		(takes-course layla lifeskills adv-higher)
		(grade c layla lifeskills adv-higher)
		(takes-course layla chemistry national-five)
		(grade b layla chemistry national-five)
		(takes-course layla spanish higher)
		(grade c layla spanish higher)
		(uses-strategy layla project-based)
		(takes-course jesse numeracy national-five)
		(grade a jesse numeracy national-five)
		(takes-course jesse textiles national-four)
		(grade p jesse textiles national-four)
		(takes-course jesse english adv-higher)
		(grade a jesse english adv-higher)
		(takes-course jesse maths year-three)
		(grade p jesse maths year-three)
		(takes-course jesse landscape-gardening year-two)
		(grade p jesse landscape-gardening year-two)
		(uses-strategy jesse blended-learning)
		(takes-course james gaelic national-five)
		(grade c james gaelic national-five)
		(takes-course james geography national-five)
		(grade b james geography national-five)
		(takes-course james urdu national-four)
		(grade p james urdu national-four)
		(takes-course james admin-it year-one)
		(grade p james admin-it year-one)
		(takes-course james maths higher)
		(grade a james maths higher)
		(uses-strategy james gamification)
		(takes-course ivy graph-comm national-five)
		(grade b ivy graph-comm national-five)
		(takes-course ivy art-design year-three)
		(grade p ivy art-design year-three)
		(takes-course ivy music-tech adv-higher)
		(grade b ivy music-tech adv-higher)
		(takes-course ivy german year-one)
		(grade p ivy german year-one)
		(takes-course ivy latin national-five)
		(grade a ivy latin national-five)
		(uses-strategy ivy project-based)
	)

	(:goal
		(and
			(finished-course esme music higher)
			(finished-course esme french national-four)
			(finished-course esme german national-four)
			(finished-course esme geography year-one)
			(finished-course esme music-tech national-four)
			(given-support esme improving-comms-workshop)
			(given-support esme tech-assist)
			(given-support esme gamify-learning)
			(finished-course harper landscape-gardening national-five)
			(finished-course harper landscape-gardening adv-higher)
			(finished-course harper music year-two)
			(finished-course harper graph-comm higher)
			(finished-course harper gaelic year-one)
			(given-support harper improving-comms-workshop)
			(finished-course henry chemistry adv-higher)
			(finished-course henry comp-sci adv-higher)
			(finished-course henry modern-studies adv-higher)
			(finished-course henry gaelic year-two)
			(finished-course henry philosophy adv-higher)
			(given-support henry improving-comms-workshop)
			(given-support henry tech-assist)
			(given-support henry gamify-learning)
			(finished-course george textiles year-two)
			(finished-course george dance year-two)
			(finished-course george philosophy adv-higher)
			(finished-course george phys-ed year-one)
			(finished-course george admin-it year-two)
			(given-support george gamify-learning)
			(finished-course erin chemistry year-two)
			(finished-course erin politics year-two)
			(finished-course erin comp-sci national-four)
			(finished-course erin graph-comm national-four)
			(finished-course erin design-manufacture adv-higher)
			(given-support erin improving-comms-workshop)
			(finished-course zara maths year-two)
			(finished-course zara landscape-gardening year-three)
			(finished-course zara mandarin national-four)
			(finished-course zara esol year-one)
			(finished-course zara graph-comm year-three)
			(given-support zara gamify-learning)
			(finished-course ella textiles adv-higher)
			(finished-course ella music year-three)
			(finished-course ella french higher)
			(finished-course ella music-tech year-two)
			(finished-course ella italian national-five)
			(given-support ella improving-comms-workshop)
			(finished-course caleb home-economics year-one)
			(finished-course caleb business-management adv-higher)
			(finished-course caleb textiles national-five)
			(finished-course caleb gaelic national-five)
			(finished-course caleb chemistry national-five)
			(given-support caleb improving-comms-workshop)
			(given-support caleb tech-assist)
			(given-support caleb gamify-learning)
			(finished-course beatrice mandarin year-one)
			(finished-course beatrice urdu national-five)
			(finished-course beatrice phys-ed year-three)
			(finished-course beatrice pc-passport national-five)
			(finished-course beatrice geography year-two)
			(given-support beatrice improving-comms-workshop)
			(given-support beatrice pomo)
			(finished-course louis spanish adv-higher)
			(finished-course louis physics year-two)
			(finished-course louis landscape-gardening national-four)
			(finished-course louis drama adv-higher)
			(finished-course louis rmps national-five)
			(given-support louis gamify-learning)
			(finished-course evan german year-one)
			(finished-course evan music year-one)
			(finished-course evan maths year-one)
			(finished-course evan geography year-two)
			(finished-course evan politics national-four)
			(given-support evan improving-comms-workshop)
			(finished-course matilda design-manufacture year-one)
			(finished-course matilda biology year-three)
			(finished-course matilda cantonese year-one)
			(finished-course matilda biology national-four)
			(finished-course matilda biology year-three)
			(given-support matilda improving-comms-workshop)
			(given-support matilda pomo)
			(finished-course sebastian geography national-five)
			(finished-course sebastian geography national-five)
			(finished-course sebastian philosophy national-four)
			(finished-course sebastian maths year-two)
			(finished-course sebastian admin-it national-five)
			(given-support sebastian gamify-learning)
			(finished-course finn biology higher)
			(finished-course finn lifeskills national-four)
			(finished-course finn biology national-four)
			(finished-course finn admin-it higher)
			(finished-course finn physics year-two)
			(given-support finn improving-comms-workshop)
			(given-support finn pomo)
			(finished-course florence physics national-four)
			(finished-course florence design-manufacture national-four)
			(finished-course florence english national-five)
			(finished-course florence rmps year-three)
			(finished-course florence maths national-five)
			(given-support florence improving-comms-workshop)
			(finished-course iris business-management adv-higher)
			(finished-course iris practical-woodwork year-three)
			(finished-course iris biology year-three)
			(finished-course iris rmps year-two)
			(finished-course iris urdu higher)
			(given-support iris improving-comms-workshop)
			(finished-course reuben esol year-one)
			(finished-course reuben mandarin year-three)
			(finished-course reuben esol national-four)
			(finished-course reuben dance year-two)
			(finished-course reuben italian adv-higher)
			(given-support reuben improving-comms-workshop)
			(given-support reuben pomo)
			(finished-course eliza italian year-one)
			(finished-course eliza art-design national-five)
			(finished-course eliza phys-ed national-four)
			(finished-course eliza mandarin adv-higher)
			(finished-course eliza italian year-one)
			(given-support eliza gamify-learning)
			(finished-course cody english year-one)
			(finished-course cody comp-sci national-four)
			(finished-course cody home-economics year-three)
			(finished-course cody home-economics national-five)
			(finished-course cody drama national-four)
			(given-support cody gamify-learning)
			(finished-course toby numeracy higher)
			(finished-course toby biology national-five)
			(finished-course toby italian adv-higher)
			(finished-course toby pc-passport higher)
			(finished-course toby admin-it adv-higher)
			(given-support toby improving-comms-workshop)
			(finished-course hannah music national-four)
			(finished-course hannah phys-ed national-four)
			(finished-course hannah history year-three)
			(finished-course hannah italian national-four)
			(finished-course hannah history year-one)
			(given-support hannah improving-comms-workshop)
			(finished-course scarlett german year-two)
			(finished-course scarlett urdu higher)
			(finished-course scarlett phys-ed higher)
			(finished-course scarlett politics year-one)
			(finished-course scarlett french year-two)
			(given-support scarlett gamify-learning)
			(finished-course oscar french year-three)
			(finished-course oscar mandarin year-three)
			(finished-course oscar history higher)
			(finished-course oscar french year-three)
			(finished-course oscar french year-one)
			(given-support oscar improving-comms-workshop)
			(finished-course thea lifeskills year-two)
			(finished-course thea practical-woodwork national-five)
			(finished-course thea politics year-two)
			(finished-course thea design-manufacture year-one)
			(finished-course thea spanish year-three)
			(given-support thea improving-comms-workshop)
			(given-support thea pomo)
			(finished-course jacob chemistry national-five)
			(finished-course jacob rmps year-two)
			(finished-course jacob philosophy higher)
			(finished-course jacob music-tech year-one)
			(finished-course jacob history adv-higher)
			(given-support jacob tech-assist)
			(finished-course elara esol adv-higher)
			(finished-course elara numeracy year-three)
			(finished-course elara spanish higher)
			(finished-course elara graph-comm higher)
			(finished-course elara pc-passport national-five)
			(given-support elara improving-comms-workshop)
			(given-support elara pomo)
			(finished-course layla practical-woodwork year-one)
			(finished-course layla design-manufacture year-two)
			(finished-course layla lifeskills adv-higher)
			(finished-course layla chemistry national-five)
			(finished-course layla spanish higher)
			(given-support layla improving-comms-workshop)
			(finished-course jesse numeracy national-five)
			(finished-course jesse textiles national-four)
			(finished-course jesse english adv-higher)
			(finished-course jesse maths year-three)
			(finished-course jesse landscape-gardening year-two)
			(given-support jesse improving-comms-workshop)
			(given-support jesse tech-assist)
			(given-support jesse gamify-learning)
			(finished-course james gaelic national-five)
			(finished-course james geography national-five)
			(finished-course james urdu national-four)
			(finished-course james admin-it year-one)
			(finished-course james maths higher)
			(given-support james gamify-learning)
			(finished-course ivy graph-comm national-five)
			(finished-course ivy art-design year-three)
			(finished-course ivy music-tech adv-higher)
			(finished-course ivy german year-one)
			(finished-course ivy latin national-five)
			(given-support ivy improving-comms-workshop)
		)
	)

	(:metric maximize (cost))
)
